# tutorial 16

In [25]:
import numpy as np

In [27]:
#exercise 1

a=np.arange(24).reshape(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [29]:
#getting the mask , applying the mask on the specific location
a[a%3==0]=0

In [30]:
a

array([[ 0,  1,  2,  0,  4,  5],
       [ 0,  7,  8,  0, 10, 11],
       [ 0, 13, 14,  0, 16, 17],
       [ 0, 19, 20,  0, 22, 23]])

In [31]:
#exercise 2
b=np.arange(24).reshape(4,6)

In [32]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [35]:
#getting the mask , applying the mask on the specific location
b[b%3==0]=b[b%3==0]*2

In [37]:
b

array([[ 0,  1,  2,  6,  4,  5],
       [12,  7,  8, 18, 10, 11],
       [24, 13, 14, 30, 16, 17],
       [36, 19, 20, 42, 22, 23]])