# tutorial 15

In [39]:
import numpy as np
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

# example 1

In [40]:
a[[False,True,True,False,False,True]]

array([1, 2, 5])

# example 2

In [42]:
a=np.arange(10)

In [43]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
a[a>4]

array([5, 6, 7, 8, 9])

In [50]:
a[a%2==0]

array([0, 2, 4, 6, 8])

# example 3

In [54]:
a=np.arange(18).reshape(6,3)

In [55]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [56]:
a[a%3==0]

array([ 0,  3,  6,  9, 12, 15])