# tutorial 18

In [32]:
import numpy as np

In [39]:
#np.amin
#on 1 d array
a=np.arange(10,50)
np.min(a)

10

In [41]:
#np.amin
#on 2 d array

b=np.arange(50).reshape(10,5)

In [43]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [44]:
#np.amin on overall array
np.amin(b)

0

In [45]:
#np.amin on axis wise
np.amin(b,axis=0)

array([0, 1, 2, 3, 4])

In [46]:
#np.amin on axis wise
np.amin(b,axis=1)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [49]:
#np.max on overall array

a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.amax(a)

9

In [52]:
#np.amax 2d array on axis wise
a=np.arange(50).reshape(10,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [53]:
np.amax(a,axis=0)

array([45, 46, 47, 48, 49])

In [56]:
np.amax(a,axis=1)

array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49])