# tutorial 20

In [1]:
import numpy as np

In [10]:
#argmin in 0 axis
#exercise 1
a=np.arange(20).reshape(5,4)

In [11]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [5]:
a.argmin(axis=0)

array([0, 0, 0, 0])

In [28]:
#exercise 2
b=np.array([[1,4,5],[2,0,1],[0,2,1]])

In [29]:
b

array([[1, 4, 5],
       [2, 0, 1],
       [0, 2, 1]])

In [30]:
b.argmin(axis=0)

array([2, 1, 1])

In [9]:
#argimn on 1 st axis
#exercise 3

array([[1, 4, 5],
       [2, 0, 1],
       [0, 2, 1]])

In [15]:
b.argmin(axis=1)

array([0, 1, 0])

In [16]:
np.argmax??

In [17]:
#exercise 1
#apply argmax on axis=0

a=np.arange(20).reshape(4,5)

In [19]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [20]:
a.argmax(axis=0)

array([3, 3, 3, 3, 3])

In [21]:
#exercise 2
b=np.array([[1,4,5],[2,0,1],[0,2,1]])

In [23]:
b

array([[1, 4, 5],
       [2, 0, 1],
       [0, 2, 1]])

In [24]:
b.argmax(axis=0)

array([1, 0, 0])

In [25]:
#exercise 3
#apply argmax on axis=1

a=np.arange(20).reshape(4,5)

In [26]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [27]:
a.argmax(axis=1)

array([4, 4, 4, 4])