# tutorial 7

In [1]:
import numpy as np

In [2]:
#1d array
a=np.array([1,3,5,9])

In [7]:
#CONVERT 1D ARRAY INTO 2D ARRAY

b=a.reshape(2,2)
b

array([[1, 3],
       [5, 9]])

In [9]:
#2d array 

c=np.array([a,a])
c

array([[1, 3, 5, 9],
       [1, 3, 5, 9]])

In [11]:
#convert 2d array into 1d array
d=c.reshape(8,)
d

array([1, 3, 5, 9, 1, 3, 5, 9])

In [15]:
#convert 2d array into 3d array
e=c.reshape(1,2,4)

In [16]:
e

array([[[1, 3, 5, 9],
        [1, 3, 5, 9]]])

In [17]:
c

array([[1, 3, 5, 9],
       [1, 3, 5, 9]])

In [18]:
c=np.array([a,a,a,a])

In [19]:
c

array([[1, 3, 5, 9],
       [1, 3, 5, 9],
       [1, 3, 5, 9],
       [1, 3, 5, 9]])

In [20]:
#convert 2d array into 3d array
e=c.reshape(2,4,2)

In [21]:
e

array([[[1, 3],
        [5, 9],
        [1, 3],
        [5, 9]],

       [[1, 3],
        [5, 9],
        [1, 3],
        [5, 9]]])

In [23]:
a=np.arange(30)

In [24]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [26]:
a.reshape(2,3,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])